CREATE DATABASE IF NOT EXISTS db_politicas DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE db_politicas;

CREATE TABLE IF NOT EXISTS TB_LOCALES(
cod_local varchar(5) NOT NULL,
cod_cia	varchar(3) NOT NULL,
descripcion varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_LOCALES
  ADD PRIMARY KEY (cod_local);

INSERT INTO TB_LOCALES VALUES('C58','007','C58-PUNO LIMA 4');
INSERT INTO TB_LOCALES VALUES('C54','007','C54-JULIACA SAN ROMAN 2');

CREATE TABLE IF NOT EXISTS TB_ESTADO_SEMAFORO (
cod_est_semaforo int(1) NOT NULL,
descripcion varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_ESTADO_SEMAFORO
  ADD PRIMARY KEY (cod_est_semaforo);

INSERT INTO TB_ESTADO_SEMAFORO VALUES(0,'PENDIENTE');
INSERT INTO TB_ESTADO_SEMAFORO VALUES(1,'TERMINADO');

CREATE TABLE IF NOT EXISTS TB_SEMAFORO (
cod_semaforo int(2) NOT NULL,
semaforo			varchar(30) NOT NULL,
cod_est_semaforo 		int(1) NOT NULL,
rango_dias varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_SEMAFORO
  ADD PRIMARY KEY (cod_semaforo);

ALTER TABLE TB_SEMAFORO
	ADD FOREIGN KEY(cod_est_semaforo) REFERENCES TB_ESTADO_SEMAFORO(cod_est_semaforo);

INSERT INTO TB_SEMAFORO VALUES(1,'VERDE',1,'0 DIAS');
INSERT INTO TB_SEMAFORO VALUES(2,'AMARILLO',0,'ENTRE 5 Y 10 DIAS');
INSERT INTO TB_SEMAFORO VALUES(3,'NARANJA',0,'ENTRE 10 Y 20 DÍAS');
INSERT INTO TB_SEMAFORO VALUES(4,'ROJO',0,'MAYOR A 20 DIAS');

CREATE TABLE IF NOT EXISTS TB_POLITICAS (
cod_politicas int(2) NOT NULL,
descripcion varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_POLITICAS
  ADD PRIMARY KEY (cod_politicas);

INSERT INTO TB_POLITICAS VALUES(1,'GUIAS DE TRANSFERENCIA');
INSERT INTO TB_POLITICAS VALUES(2,'DEPOSITO BANCARIO');
INSERT INTO TB_POLITICAS VALUES(3,'REMESAS FUERA DE RANGO');
INSERT INTO TB_POLITICAS VALUES(4,'CIERRE DIA PENDIENTE');
INSERT INTO TB_POLITICAS VALUES(5,'ACUMULACION DE DEFICIT');
INSERT INTO TB_POLITICAS VALUES(6,'ANULACION DE CUADRATURA');
INSERT INTO TB_POLITICAS VALUES(7,'ASL PENDIENTE');
INSERT INTO TB_POLITICAS VALUES(8,'OC DIRECTA');
INSERT INTO TB_POLITICAS VALUES(9,'RECEPCION DE ENTREGAS');
INSERT INTO TB_POLITICAS VALUES(10,'GUIAS DE DEVOLUCION');

CREATE TABLE IF NOT EXISTS TB_TIPO_PERSONA(
cod_tipo_persona	int(2) NOT NULL,
descripcion	varchar(50)	NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_TIPO_PERSONA
	ADD PRIMARY KEY(cod_tipo_persona);

INSERT INTO TB_TIPO_PERSONA VALUES(1,'ADMINISTRADOR');
INSERT INTO TB_TIPO_PERSONA VALUES(2,'SUBGERENTE ZONAL');
INSERT INTO TB_TIPO_PERSONA VALUES(3,'JEFE ZONAL');

CREATE TABLE IF NOT EXISTS TB_ESTADO(
cod_estado	int(1) NOT NULL,
descripcion	varchar(50)	NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_ESTADO
	ADD PRIMARY KEY(cod_estado);

INSERT INTO TB_ESTADO VALUES(0,'INACTIVO');
INSERT INTO TB_ESTADO VALUES(1,'ACTIVO');

CREATE TABLE IF NOT EXISTS TB_PERSONA(
dni					varchar(8) NOT NULL,
cod_tipo_persona int(2) NOT NULL,
nombre			varchar(50) NOT NULL,
paterno			varchar(50) NOT NULL,
materno		  varchar(50) NOT NULL,
cod_estado			int(1) NOT NULL,
fecha_reg		datetime
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_PERSONA
  ADD PRIMARY KEY (dni);

ALTER TABLE TB_PERSONA
  ADD FOREIGN KEY(cod_tipo_persona) REFERENCES TB_TIPO_PERSONA(cod_tipo_persona);

ALTER TABLE TB_PERSONA
  ADD FOREIGN KEY(cod_estado) REFERENCES TB_ESTADO(cod_estado);

INSERT INTO TB_PERSONA VALUES('40601632',3,'IVOONE MILAGROS','RINCON','SANTOS',1,SYSDATE());

CREATE TABLE IF NOT EXISTS usuarios (
  id int(11) NOT NULL,
  usuario varchar(30) NOT NULL,
  password varchar(130) NOT NULL,
-- nombre varchar(100) NOT NULL,
  correo varchar(80) NOT NULL,
  last_session datetime DEFAULT NULL,
  activacion int(11) NOT NULL DEFAULT '0',
  token varchar(40) NOT NULL,
  token_password varchar(100) DEFAULT NULL,
  password_request int(11) DEFAULT '0',
	dni varchar(8) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE usuarios
  ADD PRIMARY KEY (id);

ALTER TABLE usuarios
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE usuarios
  ADD FOREIGN KEY(dni) REFERENCES TB_PERSONA(dni);

CREATE TABLE IF NOT EXISTS TB_CAB_DOCUMENTOS (
cod_doc varchar(7) NOT NULL,
num_doc_ori	varchar(15) NOT NULL,-- numero documento origen
loc_ori varchar(5),
loc_dest varchar(5),
total_prod int(3), 
fec_crea_origen datetime,
jzona_ori varchar(8),
jzona_dest varchar(8),
mail_jefe_o varchar(30),
mail_gerente_o varchar(30),
mail_jefe_d varchar(30),
mail_gerente_d varchar(30)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_CAB_DOCUMENTOS
  ADD PRIMARY KEY (cod_doc);

ALTER TABLE TB_CAB_DOCUMENTOS 
	ADD FOREIGN KEY(loc_ori) REFERENCES TB_LOCALES(cod_local);

ALTER TABLE TB_CAB_DOCUMENTOS 
	ADD FOREIGN KEY(loc_dest) REFERENCES TB_LOCALES(cod_local);

ALTER TABLE TB_CAB_DOCUMENTOS 
	ADD FOREIGN KEY(jzona_ori) REFERENCES TB_PERSONA(dni);

ALTER TABLE TB_CAB_DOCUMENTOS 
	ADD FOREIGN KEY(jzona_dest) REFERENCES TB_PERSONA(dni);

INSERT INTO TB_CAB_DOCUMENTOS VALUES('0000001','3330009989','C58','C54',256,'2018-05-14','40601632','40601632','dflores','mquispe','dflores','mgomez');

CREATE TABLE IF NOT EXISTS TB_DET_DOCUMENTOS (
cod_det_doc int(10) NOT NULL,
cod_doc varchar(7) NOT NULL,
cod_prod varchar(10) NOT NULL, 
desc_prod varchar(100) NOT NULL, 
desc_unid_present varchar(100),
cant_mov int(6),
val_frac int(4)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_DET_DOCUMENTOS
  ADD PRIMARY KEY (cod_det_doc);

ALTER TABLE TB_DET_DOCUMENTOS
  MODIFY cod_det_doc int(10) NOT NULL AUTO_INCREMENT;

ALTER TABLE TB_DET_DOCUMENTOS 
	ADD FOREIGN KEY(cod_doc) REFERENCES TB_CAB_DOCUMENTOS(cod_doc);

INSERT INTO TB_DET_DOCUMENTOS VALUES(1,'0000001','512587','DORSOF 2% OFT','FCO 5 ML','1','1');
INSERT INTO TB_DET_DOCUMENTOS VALUES(2,'0000001','134123','DOLONET FORTE 400 MG','CJA 100 CAP','100','100');
INSERT INTO TB_DET_DOCUMENTOS VALUES(3,'0000001','132153','DR ZAID COL BABY S/ALCOHOL','FCO 200 ML','2','100');
INSERT INTO TB_DET_DOCUMENTOS VALUES(4,'0000001','137857','DR ZAID TALCO','FCO 200 GR','3','3');
INSERT INTO TB_DET_DOCUMENTOS VALUES(5,'0000001','132186','DR ZAID TALCO','FCO 600 GR','3','3');

CREATE TABLE IF NOT EXISTS TB_ESTADO_DOCUMENTOS(
cod_estado_doc 			INT(7) NOT NULL,
cod_politicas 			int(2) NOT NULL,
cod_doc 	varchar(7) NOT NULL,
cod_semaforo 				int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TB_ESTADO_DOCUMENTOS
  ADD PRIMARY KEY (cod_estado_doc);

ALTER TABLE TB_ESTADO_DOCUMENTOS
  MODIFY cod_estado_doc int(7) NOT NULL AUTO_INCREMENT;

ALTER TABLE TB_ESTADO_DOCUMENTOS
	ADD FOREIGN KEY(cod_politicas) REFERENCES TB_POLITICAS(cod_politicas);

ALTER TABLE TB_ESTADO_DOCUMENTOS
	ADD FOREIGN KEY(cod_doc) REFERENCES TB_CAB_DOCUMENTOS(cod_doc);

ALTER TABLE TB_ESTADO_DOCUMENTOS
	ADD FOREIGN KEY(cod_semaforo) REFERENCES TB_SEMAFORO(cod_semaforo);

INSERT INTO TB_ESTADO_DOCUMENTOS VALUES(1,'1','0000001','2');
commit;